# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE UI will override any settings in this file.

# Enables AndroidX support
android.useAndroidX=true

# Enables non-transitive R class for faster builds
android.nonTransitiveRClass=true

# JVM args for Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style
kotlin.code.style=official
